### ISSUE TITLE
Migration to MIT License

### ISSUE THREAD

**Issue by RhysB** [RhysB/Discord-Bot-Chatbridge#11]
I hope to migrate this project from GPL to MIT and thus need the permission of anyone who has contributed.

Can the following people please respond if they consent:

- @ScarletLovell 
- @Strultz 
- @Owen2k6 

MIT License: https://choosealicense.com/licenses/mit/

**Comment by Owen2k6** [comment]
im fine with it muffin man

**Comment by ScarletLovell** [comment]
Fine with me

**Comment by Strultz** [comment]
yes (i forgor)

**Comment by RhysB** [comment]
License changed
